/**
 * PMD (Power Mobility Device) Product Catalog
 *
 * Static catalog of PMD offerings with HCPCS codes, weight capacities,
 * seat types, brochure links, and product images. Mirrors the "PMD Offerings"
 * spreadsheet used in the original PPD Apps Script workflow.
 */

export interface PmdProduct {
  features: string;
  hcpcs: string;
  weightCapacity: string;   // e.g., "285" or "286-429"
  seatType: string;         // C/C, S/C, S/S, etc.
  brochureUrl: string;
  imageUrl: string;
  portable: boolean;
  foldable: boolean;
  seatDimensions: string;
  colors: string;
  leadTime: string;
  notes: string;
}

export const PMD_CATALOG: PmdProduct[] = [
  {
    features: 'Power Scooter (Up to 285 lbs)',
    hcpcs: 'K0800',
    weightCapacity: '285',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0800%20Pride%20Ultra%20X%20Brochure%20(mfg).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Pride%20Go-Go%20Ultra%20X%203-Wheel%20K0800.jpg?raw=true',
    portable: true, foldable: true,
    seatDimensions: '17x17',
    colors: 'Black',
    leadTime: '2-3 weeks',
    notes: 'Flight Compatibility - Pt will have to check with Airline before flying',
  },
  {
    features: 'Power Scooter (Up to 325 lbs)',
    hcpcs: 'K0801',
    weightCapacity: '325',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0801%20-%20Pride%20Go-Go%20Sport%20Brochure%20(mfg).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Pride%20Go-Go%20Sport%203-Wheel%20K0801.jpg?raw=true',
    portable: true, foldable: true,
    seatDimensions: '17x17',
    colors: 'Red, Blue',
    leadTime: '2-3 weeks',
    notes: '',
  },
  {
    features: 'Std Power Chair (Up to 285 lbs)',
    hcpcs: 'K0821',
    weightCapacity: '285',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0821%20Pride%20Go%20Chair%20Med%20Brochure%20(mfg).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Pride%20Go%20Chair%20MED%20K0821.jpg?raw=true',
    portable: true, foldable: true,
    seatDimensions: '18x18 (Pride), 20x18 (Pride), 18x17.5 (Shoprider)',
    colors: 'Black',
    leadTime: '2-3 weeks',
    notes: '93 lbs, heaviest piece 36 lbs',
  },
  {
    features: 'Std Power Chair (Up to 285 lbs)',
    hcpcs: 'K0822',
    weightCapacity: '285',
    seatType: 'S/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0823%20Brochure%20(mfg).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Jazzy%20Elite%20ES%20K0823.jpg?raw=true',
    portable: true, foldable: true,
    seatDimensions: '16x18, 18x18, 20x18 (Pride)',
    colors: 'Red',
    leadTime: '2-3 weeks',
    notes: 'Basket $118, Cup Holder $35, Saddle Bag $40',
  },
  {
    features: 'Std Power Chair (Up to 285 lbs)',
    hcpcs: 'K0823',
    weightCapacity: '285',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0823%20Brochure%20(mfg).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Jazzy%20Elite%20ES%20K0823.jpg?raw=true',
    portable: true, foldable: true,
    seatDimensions: '16x18, 18x18, 20x18 (Pride), 19x18 (Shoprider)',
    colors: 'Red',
    leadTime: '2-3 weeks',
    notes: 'Basket $118, Cup Holder $35, Saddle Bag $40',
  },
  {
    features: 'Std Power Chair (286-429 lbs)',
    hcpcs: 'K0824',
    weightCapacity: '286-429',
    seatType: 'S/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0825%20Jazzy%20Elite%20HD%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Jazzy%20Elite%20HD%20K0825.jpg?raw=true',
    portable: true, foldable: true,
    seatDimensions: '20x20, 22x20 (Pride)',
    colors: 'Red',
    leadTime: '2-3 weeks',
    notes: '',
  },
  {
    features: 'Std Power Chair (286-429 lbs)',
    hcpcs: 'K0825',
    weightCapacity: '286-429',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0825%20Jazzy%20Elite%20HD%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Jazzy%20Elite%20HD%20K0825.jpg?raw=true',
    portable: false, foldable: true,
    seatDimensions: '20x20, 22x20 (Pride), 21x21 (Shoprider)',
    colors: 'Red',
    leadTime: '2-3 weeks',
    notes: 'Pride chair weight 225lbs, heaviest piece 99 lbs',
  },
  {
    features: 'Std Power Chair (429-570 lbs)',
    hcpcs: 'K0826',
    weightCapacity: '429-570',
    seatType: 'S/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0827%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Merits%20Atlantis%20K0827.png?raw=true',
    portable: false, foldable: true,
    seatDimensions: '24x20',
    colors: 'Blue, Red',
    leadTime: '2-3 weeks',
    notes: '',
  },
  {
    features: 'Std Power Chair (429-570 lbs)',
    hcpcs: 'K0827',
    weightCapacity: '429-570',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0827%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Merits%20Atlantis%20K0827.png?raw=true',
    portable: false, foldable: true,
    seatDimensions: '24x20',
    colors: 'Blue, Red',
    leadTime: '2-3 weeks',
    notes: '',
  },
  {
    features: 'Power Chair w/ Tilt (Up to 285 lbs)',
    hcpcs: 'K0835',
    weightCapacity: '285',
    seatType: 'S/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0836%20UMS%20Brochure.png?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Shoprider%20XLR-14%20K0836_tilt.jpg?raw=true',
    portable: false, foldable: true,
    seatDimensions: '18x18, 18x20, 20x20',
    colors: 'Red, Black, Blue, Pewter',
    leadTime: '2-3 weeks',
    notes: 'No Cup Holder, Special Controls/Joystick from manufacturer',
  },
  {
    features: 'Power Chair w/ Tilt (Up to 285 lbs)',
    hcpcs: 'K0836',
    weightCapacity: '285',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0836%20UMS%20Brochure.png?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Shoprider%20XLR-14%20K0836_tilt.jpg?raw=true',
    portable: false, foldable: true,
    seatDimensions: '18x17.5, 19x18, 21x21, 23x19',
    colors: 'Red, Black, Blue',
    leadTime: '2-3 weeks',
    notes: 'No Cup Holder, Special Controls/Joystick from manufacturer',
  },
  {
    features: 'Power Chair w/ Tilt (286-429 lbs)',
    hcpcs: 'K0837',
    weightCapacity: '286-429',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0837%20Merits%20Vision%20Ultra%20HD%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Merits%20Vision%20Ultra%20HD%20K0837.jpg?raw=true',
    portable: false, foldable: true,
    seatDimensions: '18"-25" wide x 16"-22" deep',
    colors: 'Red, Blue, White, Grey',
    leadTime: '2-3 weeks',
    notes: 'Just Manual ELR No Footplate / No option to add O2 tank holder',
  },
  {
    features: 'Power Chair w/ Tilt (286-429 lbs)',
    hcpcs: 'K0838',
    weightCapacity: '286-429',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0837%20Merits%20Vision%20Ultra%20HD%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@85319a5229adc0e586111c8ed5a28323b7821ce9/Merits%20Vision%20Ultra%20HD%20K0837.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '20"-26" wide x 17"-23" deep (custom)',
    colors: 'Red, Blue, White, Grey',
    leadTime: '2-3 weeks',
    notes: 'Just Manual ELR No Footplate / No option to add O2 tank holder',
  },
  {
    features: 'Power Chair w/ Tilt & Recline (Up to 285 lbs)',
    hcpcs: 'K0841',
    weightCapacity: '285',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0861%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20K0861.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '16"-22" wide x 17"-23" deep (custom)',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: '',
  },
  {
    features: 'Power Chair w/ Tilt & Recline (Up to 285 lbs)',
    hcpcs: 'K0842',
    weightCapacity: '285',
    seatType: 'C/C',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0861%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20K0861.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '16"-22" wide x 17"-23" deep (custom)',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: '',
  },
  {
    features: 'Power Chair w/ Tilt & Recline (286-429 lbs)',
    hcpcs: 'K0843',
    weightCapacity: '286-429',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0862%20UMS.jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20HD%20K0862.jpg',
    portable: false, foldable: false,
    seatDimensions: '20"-24" wide x 17"-22" deep (Invacare), 20"-26" wide x 18"-22" deep (Amysystems)',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: '',
  },
  {
    features: 'Power Chair w/ Tilt (Up to 285 lbs) [Group 3]',
    hcpcs: 'K0856',
    weightCapacity: '285',
    seatType: '',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0861%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20K0861.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: '',
  },
  {
    features: 'Power Chair w/ Tilt (286-380 lbs) [Group 3]',
    hcpcs: 'K0858',
    weightCapacity: '286-380',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0858%20-%20Invacare%20TDX%20SP%202%20HD%20tilt%20only.jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20HD%20K0862_lifted.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '20"-26" wide x 17"-23" deep (custom)',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: 'Add Footplate with Manual ELR',
  },
  {
    features: 'Power Chair w/ Tilt & Recline (Up to 285 lbs) [Group 3]',
    hcpcs: 'K0861',
    weightCapacity: '285',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0861%20Brochure%20(UMS).jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20K0861.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '16"-22" wide x 17"-23" deep (custom)',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: 'Cup Holder OOP $50, Power Seat Elevation OOP $2500, Attendant control OOP $700, Light Kit OOP $700, Leg Strap K0038, Special Joystick E2323',
  },
  {
    features: 'Power Chair w/ Tilt & Recline (286-429 lbs) [Group 3]',
    hcpcs: 'K0862',
    weightCapacity: '286-429',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0862%20UMS.jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Invacare%20TDX%20SP2%20HD%20K0862.jpg',
    portable: true, foldable: false,
    seatDimensions: '20"-24" wide x 17"-22" deep (Invacare), 20"-26" wide x 18"-22" deep (Amysystems)',
    colors: 'Obsidian Black, Ruby Red, Peacock Blue, Purple Passion, Denim Navy, Lime Twist, Arctic Blue',
    leadTime: '3-4 weeks',
    notes: 'Cup Holder OOP $50, Power Seat Elevation OOP $2500, Attendant control OOP $700, Leg Strap K0038',
  },
  {
    features: 'Power Chair w/ Tilt & Recline (429-550 lbs) [Group 3]',
    hcpcs: 'K0863',
    weightCapacity: '429-550',
    seatType: 'S/S',
    brochureUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/K0863%20AllTrack%20HD%203%20AmyLior%20Brochure%20UMS.jpg?raw=true',
    imageUrl: 'https://cdn.jsdelivr.net/gh/robinchoudhuryums/product-images@main/Amysystems%20Alltrack%20HD3%20K0863.jpg?raw=true',
    portable: false, foldable: false,
    seatDimensions: '20"-28" wide x 18"-24" deep (custom)',
    colors: 'Pink, Maroon, Red, Cobalt Blue, Orange, Indigo Blue, Black, Lime Green',
    leadTime: '6-8 weeks',
    notes: '',
  },
];

/**
 * Look up a product by HCPCS code. Returns all matching products
 * (there may be multiple seat type variants for the same code).
 */
export function getProductsByHcpcs(hcpcs: string): PmdProduct[] {
  return PMD_CATALOG.filter(p => p.hcpcs === hcpcs);
}

/**
 * Get the first product matching a HCPCS code (for substitution lookups).
 */
export function getProductByHcpcs(hcpcs: string): PmdProduct | undefined {
  return PMD_CATALOG.find(p => p.hcpcs === hcpcs);
}
